name: spectra_flutter
description: A new Flutter project with Serverpod.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.9.1
  spectra_client:
    path: ../spectra_client

  cupertino_icons: ^1.0.5
  fpdart: ^1.1.1
  flex_color_scheme: ^8.2.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.5.3
  iconsax: ^0.0.8
  flutter_native_splash: ^2.4.6
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1
  video_player: ^2.10.0
  toastification: ^3.0.3
  image_picker: ^1.1.2
  go_router: ^16.0.0
  flutter_dotenv: ^5.2.1
  dropdown_button2: ^2.3.9
  flutter_staggered_grid_view: ^0.7.0
  flutter_cache_manager: ^3.4.1
  loading_animation_widget: ^1.3.0
  image_cropper: ^9.1.0
  url_launcher: ^6.3.2
  pinput: ^5.0.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  path_provider: ^2.1.5
  path: ^1.9.1
  serverpod_auth_email_flutter: ^2.9.1
  serverpod_auth_shared_flutter: ^2.9.1
  carousel_slider: ^5.1.1
  visibility_detector: ^0.4.0+2
  dotted_border: ^3.1.0
  dio: ^5.9.0
  infinite_scroll_pagination: ^5.1.0
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^12.0.1
  intl: ^0.20.2
  popover: ^0.3.1

dev_dependencies:
  flutter_lints: ">=3.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  riverpod_generator: 2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/
    - assets/videos/

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans-SemiBold.otf
          weight: 600

    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
